#!/bin/bash

echo "=============================="
echo "git branch any_branch_to_create upstream/develop"
echo "=============================="
echo "git branch -D any_branch_to_delete"
echo "=============================="
echo "git push -u origin any_branch_to_push"
echo "=============================="
echo "git rebase -i HEAD~2"
echo "=============================="
echo "git remote add upstream"
echo "git fetch upstream main"
echo "git rebase -i upstream/main"
echo "=============================="
echo "Update repo's submodule"
echo "git submodule sync --recursive"
echo "git submodule update --init --recursive"
echo "=============================="
echo "checkout submodule branch of differnt remote repo"
echo "git submodule add git@github.com:any_user/repo_name.git /git/local_repo/submodule_path"
echo "cd /git/local_repo/submodule_path"
echo "git checkout some_branch origin/some_branch"
echo "=============================="
echo "git log -S 'any_keyword' /git/any_file_in_repo"
echo "=============================="
echo "git reflog --date=iso"
echo "=============================="
echo "git checkout 38b04e~1 -- /git/anyrepo/any_file"
echo "=============================="
echo "Change commit author"
echo "git commit --amend --author="email@test.com" --no-edit"
echo "=============================="
echo "change commit time to current time"
echo "git commit --amend --date=now"